window.mealData = [
  {
    id: 1,
    category: 'campus',
    type: 'cafe',
    name: '카페드림',
    position: '학술정보원 2층',
    image: 'assets/images/meal/cafe_dream.jpg',
    description: '학정 이용 시 접근성이 좋고, 의외의 핫도그 맛집!',
  },
  {
    id: 2,
    category: 'campus',
    type: 'cafe',
    name: '파리바게뜨',
    position: '학생회관 1층',
    image: 'assets/images/meal/paris_baguette.jpg',
    description: '오전 7시 오픈, 이른 아침 해결하기 좋은 곳',
  },
  {
    id: 3,
    category: 'campus',
    type: 'cafe',
    name: '와플대학',
    position: '학생회관 1층',
    image: 'assets/images/meal/waffle_university.jpg',
    description: '학식 먹고 후식으로 와플 먹는 것 어때요?',
  },
  {
    id: 4,
    category: 'campus',
    type: 'cafe',
    name: '제주몰빵',
    position: '학생회관 2층',
    image: 'assets/images/meal/cafe_jeju.jpg',
    description: '아샷추 잘 하는 카페',
  },
  {
    id: 5,
    category: 'campus',
    type: 'cafe',
    name: '카페딕셔너리',
    position: '충무관 1층',
    image: 'assets/images/meal/cafe_dictionary_chungmu.jpg',
    description: '충무관 이용 시 접근성이 좋아요',
  },
  {
    id: 6,
    category: 'campus',
    type: 'cafe',
    name: '카페딕셔너리',
    position: '광개토관 지하1층',
    image: 'assets/images/meal/cafe_dictionary.jpg',
    description: '광개토관 이용 시 접근성이 좋아요',
  },
  {
    id: 7,
    category: 'campus',
    type: 'cafe',
    name: '투썸플레이스',
    position: '대양AI센터 1층',
    image: 'assets/images/meal/two_some.jpg',
    description: '대양AI센터 이용 시 접근성이 좋아요',
  },
  {
    id: 8,
    category: 'campus',
    type: 'cafe',
    name: '유캔두잇',
    position: '광개토관 15층',
    image: 'assets/images/meal/you_can_do_it.jpg',
    description: '카공하기 적합한 곳, 음식도 맛있어요',
  },
  {
    id: 9,
    category: 'campus',
    type: 'restaurant',
    name: '군자관 식당',
    position: '군자관 6층',
    image: 'assets/images/meal/gunja.jpeg',
    description: '뷔페식 식당, 양이 많고 가격도 저렴해요',
  },
  {
    id: 10,
    category: 'campus',
    type: 'restaurant',
    name: '진관홀 식당',
    position: '진관홀 지하',
    image: 'assets/images/meal/jin.jpg',
    description: '순쫄이 유명한 식당',
  },
  {
    id: 11,
    category: 'campus',
    type: 'restaurant',
    name: '학생회관 식당',
    position: '학생회관 1층',
    image: 'assets/images/meal/student_hall.png',
    description: '메뉴가 정말 다양해요',
  },
  {
    id: 12,
    category: 'offcampus',
    type: 'cafe',
    name: '보난자커피',
    position: '서울 광진구 능동로 239-1 B동 1층',
    image: 'assets/images/meal/bonanza.jpg',
  },
  {
    id: 13,
    category: 'offcampus',
    type: 'cafe',
    name: '스타벅스',
    position: '서울 광진구 능동로 243 (군자동)',
    image: 'assets/images/meal/starbucks.jpg',
  },
  {
    id: 14,
    category: 'offcampus',
    type: 'restaurant',
    name: '버거킹',
    position: '서울 광진구 능동로 245',
    image: 'assets/images/meal/burger_king.jpg',
  },
  {
    id: 15,
    category: 'offcampus',
    type: 'restaurant',
    name: '카레당',
    position: '서울 광진구 능동로 251',
    image: 'assets/images/meal/curry_dang.jpg',
  },
  {
    id: 16,
    category: 'offcampus',
    type: 'restaurant',
    name: '소사면옥',
    position: '서울 광진구 능동로 270 1층',
    image: 'assets/images/meal/sosamyeonok.jpg',
  },
  {
    id: 17,
    category: 'offcampus',
    type: 'restaurant',
    name: '맛짱마라탕',
    position: '서울 광진구 능동로 276 1층 103호',
    image: 'assets/images/meal/matjjang.jpg',
  },
  {
    id: 18,
    category: 'offcampus',
    type: 'restaurant',
    name: '군자돈까스',
    position: '서울 광진구 능동로 276 1층',
    image: 'assets/images/meal/gunja_donkkas.jpg',
  },
  {
    id: 19,
    category: 'offcampus',
    type: 'restaurant',
    name: '이이요',
    position: '서울 광진구 능동로32길6',
    image: 'assets/images/meal/eiyiyo.jpeg',
  },
  {
    id: 20,
    category: 'offcampus',
    type: 'restaurant',
    name: '세종감자탕',
    position: '서울 광진구 군자로 145 양지쇼핑',
    image: 'assets/images/meal/sejong_gamjatang.jpg',
  },
  {
    id: 21,
    category: 'offcampus',
    type: 'restaurant',
    name: '공주식당',
    position: '서울 광진구 군자로 137 목화골든빌리지',
    image: 'assets/images/meal/gongju.jpg',
  },
  {
    id: 22,
    category: 'offcampus',
    type: 'restaurant',
    name: '장원칼국수',
    position: '서울 광진구 군자로 137 장원칼국수',
    image: 'assets/images/meal/jangwon.jpg',
  },
  {
    id: 23,
    category: 'offcampus',
    type: 'restaurant',
    name: '카츠모',
    position: '서울 광진구 군자로 132 1층 102호',
    image: 'assets/images/meal/katsumo.png',
  },
  {
    id: 24,
    category: 'offcampus',
    type: 'cafe',
    name: '단지커피',
    position: '서울 광진구 군자로 133-1 1층 102호',
    image: 'assets/images/meal/danji.jpg',
  },
  {
    id: 25,
    category: 'offcampus',
    type: 'restaurant',
    name: '방이샤브샤브칼국수',
    position: '서울 광진구 군자로 106 1층',
    image: 'assets/images/meal/bangyi.JPG',
  },
  {
    id: 26,
    category: 'offcampus',
    type: 'restaurant',
    name: '채움 솥뚜껑생삼겹살',
    position: '서울 광진구 군자로 104-1',
    image: 'assets/images/meal/chaeum.jpg',
  },
  {
    id: 27,
    category: 'offcampus',
    type: 'restaurant',
    name: '또래끼리',
    position: '서울 광진구 군자로 103',
    image: 'assets/images/meal/ddorae.jpg',
  },
  {
    id: 28,
    category: 'offcampus',
    type: 'restaurant',
    name: '춘선만두',
    position: '서울 광진구 군자로 101',
    image: 'assets/images/meal/chunseon.jpg',
  },
  {
    id: 29,
    category: 'offcampus',
    type: 'restaurant',
    name: '마라대국',
    position: '서울 광진구 군자로 96',
    image: 'assets/images/meal/mara.jpg',
  },
  {
    id: 30,
    category: 'offcampus',
    type: 'restaurant',
    name: '피자스쿨',
    position: '서울 광진구 군자로 76 1층 1-1, 2호',
    image: 'assets/images/meal/pizza_school.jpg',
  },
  {
    id: 31,
    category: 'offcampus',
    type: 'restaurant',
    name: '춘천골닭갈비',
    position: '서울 광진구 군자로 70 나동 1층 105호',
    image: 'assets/images/meal/chuncheongol.jpg',
  },
  {
    id: 32,
    category: 'offcampus',
    type: 'restaurant',
    name: '미식반점',
    position: '서울 광진구 군자로 70 1층',
    image: 'assets/images/meal/misik.jpg',
  },
];
