window.mealData = [
  {
    id: 1,
    category: 'campus',
    type: 'cafe',
    name: '카페드림',
    position: '학술정보원 2층',
    image: 'assets/images/cafe_dream.jpg',
    description: '학정 이용 시 접근성이 좋고, 의외의 핫도그 맛집!',
  },
  {
    id: 2,
    category: 'campus',
    type: 'cafe',
    name: '파리바게뜨',
    position: '학생회관 1층',
    image: 'assets/images/paris_baguette.jpg',
  },
  {
    id: 3,
    category: 'campus',
    type: 'cafe',
    name: '와플대학',
    position: '학생회관 1층',
    image: 'assets/images/waffle_university.jpg',
  },
  {
    id: 4,
    category: 'campus',
    type: 'cafe',
    name: '제주몰빵',
    position: '학생회관 2층',
    image: 'assets/images/cafe_jeju.jpg',
  },
  {
    id: 5,
    category: 'campus',
    type: 'cafe',
    name: '카페딕셔너리',
    position: '충무관 1층',
    image: 'assets/images/cafe_dictionary_chungmu.jpg',
  },
  {
    id: 6,
    category: 'campus',
    type: 'cafe',
    name: '카페딕셔너리',
    position: '광개토관 지하1층',
    image: 'assets/images/cafe_dictionary.jpg',
  },
  {
    id: 7,
    category: 'campus',
    type: 'cafe',
    name: '투썸플레이스',
    position: '대양AI센터 1층',
    image: 'assets/images/two_some.jpg',
  },
  {
    id: 8,
    category: 'campus',
    type: 'cafe',
    name: '유캔두잇',
    position: '광개토관 15층',
    image: 'assets/images/you_can_do_it.jpg',
  },
  {
    id: 9,
    category: 'campus',
    type: 'restaurant',
    name: '군자관 식당',
    position: '군자관 6층',
  },
  {
    id: 10,
    category: 'campus',
    type: 'restaurant',
    name: '진관홀 식당',
    position: '진관홀 지하',
  },
  {
    id: 11,
    category: 'campus',
    type: 'restaurant',
    name: '학생회관 식당',
    position: '학생회관 1층',
  },
  {
    id: 12,
    category: 'offcampus',
    type: 'cafe',
    name: '보난자커피',
    position: '서울 광진구 능동로 239-1 B동 1층',
  },
];
